### ISSUE TITLE
Support of different output formats

### ISSUE THREAD

**Issue by SecMyth** [cddmp/cvecheck#1]
How about a parameter to serve the results in different output formats. For example, by Using python module `tabulate` one can instantly serve markdown table, latex table.
For non tables you may need other modules or prepare the output manually.

**Comment by cddmp** [comment]
Instead of using tabulate, I used a more general approach and implemented Jinja2 template support. Some examples can be found in the examples folder. This allows to create your own HTML, LaTeX or raw output templates.

Does that also satisfy your need?
